name: XPortStore
options:
  deploymentTarget:
    iOS: "13.0"
configs:
  Debug: debug
  Release: release
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: ru.xportstore.ios
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Manual
    TARGETED_DEVICE_FAMILY: "1,2"
    INFOPLIST_FILE: Info.plist
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
targets:
  XPortStore:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Assets.xcassets
      - path: Base.lproj
    settings:
      base:
        SWIFT_VERSION: "5.0"
        IPHONEOS_DEPLOYMENT_TARGET: "13.0"
